# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# POSTGRES
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# INTEGRACIONES
integrations.donadores-url=${DONADORES_URL}
integrations.donaciones-url=${DONACIONES_URL}

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics

# GRAFANA CLOUD - OTLP
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=${GRAFANA_OTLP_METRICS_URL}
management.otlp.metrics.export.headers.Authorization=${GRAFANA_OTLP_HEADERS}
management.otlp.metrics.export.step=30s
management.otlp.metrics.export.aggregation-temporality=cumulative

# Identificación
management.metrics.tags.service=donatrack-logistica
management.metrics.tags.environment=production
management.metrics.tags.component=api

# Desactivar otros exporters
management.prometheus.metrics.export.enabled=false
management.datadog.metrics.export.enabled=false

# RabbitMQ
# URL provista por CloudAMQP
spring.rabbitmq.addresses=${RABBITMQ_URL}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.default-requeue-rejected=false
